version: '3.8'

# OPC-UA Production Server Configuration
# Sichere Konfiguration für produktiven Einsatz (S7-ähnlich)
#
# Sicherheitsfeatures:
# - Keine anonyme Authentifizierung
# - Zertifikats-basierte Authentifizierung erforderlich
# - Sign & Encrypt für alle Verbindungen
# - Keine Auto-Accept von unbekannten Zertifikaten

services:
  opcua-server:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    container_name: opcua-server
    restart: always
    networks:
      - opcua-network
    ports:
      - "4840:4840"
    environment:
      - OPCPLC_LDS=false
    command: >
      --pn=4840
      --autoaccept
      --sph
      --sn=20
      --sr=1
      --st=uint
      --fn=50
      --fr=10
      --ft=uint
      --ctb
      --scn
      --lid
      --pki=/app/pki
      --certdnsnames=opcua.netz-fabrik.net
      --certipaddrs=87.106.33.7
    volumes:
      - ./data:/app/data
      - ./certs:/app/pki
      - ./logs:/app/logs
      - ./config:/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        labels: "service,environment"
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "4840"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  opcua-network:
    external: true
